[package]
name = "passman-rs"
version = "0.0.1"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
itertools = "0.12.1"
ratatui = "0.26.2"
serde = { version = "1.0.198", features = ["derive"] }
rmp-serde = "1.3.0"
serde_json = "1.0.117"
